---
# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# HUSHLINE — CI workflow

name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false
      - name: go version
        run: go version
      - name: go build
        run: go build ./...
      - name: go test
        run: go test ./...
      - name: verify fmt
        run: |
          test -z "$(gofmt -s -l . | tee /tmp/gofmt.out && cat /tmp/gofmt.out)"
